### ISSUE TITLE
Support React Native 0.69.x

### ISSUE THREAD

**Issue by wem2017** [alabsi91/reanimated-color-picker#1]
Thanks for your libs, but your example does not work with RN 0.69.4
"react-native-reanimated": "2.10.0",
"react-native-gesture-handler": "2.6.0",
- fabric is off
when drag point crash with log
![Simulator Screen Shot - iPhone 12 - 2022-09-04 at 10 38 00](https://user-images.githubusercontent.com/58833808/188296367-7af84c80-dde9-40e1-ba46-239f5f190f1f.png)

**Comment by alabsi91** [comment]
Hello @wem2017, thank you for your feedback.
- I recreated the example to match the version you have and I test it on `Android` and seems to be working just fine.
- Can you please provide a code snippet to replicate the error?

**Comment by everlaat** [comment]
I think this issue comes up while using the "Debug with Chrome" option. When using this the Javascript is actually executed in the debugger
