### ISSUE TITLE
TypeError: (0 , _reactNativeReanimated.useSharedValue) is not a function

### ISSUE THREAD

**Issue by songmenglong** [alabsi91/reanimated-color-picker#2]
![2022-09-16 18 57 46](https://user-images.githubusercontent.com/16477203/190626368-19eb5eb3-43a4-45d0-a0d1-8b1681274753.png)

Error tips `reactNativeReanimated.useSharedValue is not a function`

When I look in `ColorPicker.js`, find that `import { useAnimatedStyle, useSharedValue, withTiming } from 'react-native-reanimated';`, goto `react-native-reanimated` package, I do not find `useSharedValue`value or function, I guess its version was wrong.

**Comment by alabsi91** [comment]
Hi @songmenglong 
did you follow the installation instruction for `react-native-reanimated` package ?

**Comment by songmenglong** [comment]
> Hi @songmenglong
> 
> Please provide more information:
> 
> * which platform: `Android` `IOS` `Web` `Expo`.
> * `react-native` version.
> * `react-native-reanimated` version.
> * `react-native-gesture-handler` version.
> 
> Have you added `react-native-reanimated/plugin` to `babel.config.js` file ?

`platform`:iOS
`react-native`: 0.68.2
`react-native-reanimated`

**Comment by songmenglong** [comment]
which platform: Android IOS Web Expo.
react-native version.
react-native-reanimated version.
react-native-gesture-handler version.

**Comment by songmenglong** [comment]
which platform: Android IOS Web Expo.
iOS 
react-native version.
0.68.2
react-native-reanimated version.
2.8.0
react-native-gesture-handler version.
2.2.1
reanimated-color-picker version:
1.0.2

How to added react-native-reanimated/plugin to babel.config.js file ?

**Comment by songmenglong** [comment]
Hello alabsi91:I have installed this package 发自我的 iPhone在 2022年9月16日，23:34，Ahmed Alabsi ***@***.***> 写道：﻿
Hi @songmenglong
did you follow the installation instruction for react-native-reanimated package ?

**Comment by alabsi91** [comment]
1. Add Reanimated's Babel plugin to your `babel.config.js` 
```js
  module.exports = {
    presets: [
     //  ...
    ],
    plugins: [
     //  ...
      'react-native-reanimated/plugin',  // 👈 Reanimated plugin has to be listed last.
    ],
  };
```
2. Then reset the application's cache.
```console
npx react-native start --reset-cache
```
or if you are using `Expo`
```console
expo start -c
```

- Also check [React Native Reanimated](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation#babel-plugin) docs for more information.

**Comment by songmenglong** [comment]
Add configs, run project goto Picker page, run errors: 

![2022-09-16 18 57 46](https://user-images.githubusercontent.com/16477203/190938415-2d40b99a-b951-47d7-afe5-f67510c683e8.png)

![2022-09-19 09 49 38](https://user-images.githubusercontent.com/16477203/190938435-3a0b8501-e007-4223-ade9-47363424a0b1.png)
