### ISSUE TITLE
Swatches does not return the same color defined in "color" property

### ISSUE THREAD

**Issue by cyberdevnet** [alabsi91/reanimated-color-picker#3]
Hi!, I'm using the Swatches to assign a color to some object, the component is so defined:

```
<ColorPicker
    value={ac.dc.color.value}
    sliderThickness={25}
    thumbSize={30}
    style={{ width: '75%', justifyContent: 'center' }}
    onComplete={ac.dc.onSelectColor}>
    <Swatches
    swatchStyle={styles.swatchStyle}
    colors={PedalsColourCode}
/>
</ColorPicker>
```
the colors assigned to "colors" are the following:

```
    '#FF9800',
    '#FF5722',
    '#795548',
    '#9E9E9E',
    '#607D8B',
```
When I assign the color to my object, with onSelectColor,  the "hex" assigned is similar BUT different from that one defined.
Eg:

```
PedalsColourCode:  ["#FF9800", "#FF5722", "#795548", "#9E9E9E", "#607D8B"]
hexColourAssigned: #795649
```
The assigned hex #795649 is different from the defined #795548.

Am I missing something?

**Comment by cyberdevnet** [comment]
as a workaround I assigned in my default state the "similar" returned value.

**Comment by alabsi91** [comment]
any color will be converted to HSB color format first, in your case the color will be converted from HEX to HSB then to HEX again, and sometimes after the conversion the color will be slightly inaccurate.
