### ISSUE TITLE
Disable alpha setting at will

### ISSUE THREAD

**Issue by KxmischesDomi** [alabsi91/reanimated-color-picker#32]
### description

 There should be a setting to say if the colorpicker should support transparancy or is always to be at full visibility.

**Comment by alabsi91** [comment]
"Are you suggesting that we exclude the alpha channel from the color that was inputted in the value property? Could you please elaborate on what you have in mind?"

**Comment by KxmischesDomi** [comment]
I want to be able to disable the alpha setting in the input widget. For example the hex input, rgb instead of rgba. I do not want to support any transparancy in my application and so the user shall not be able to set any.

**Comment by alabsi91** [comment]
Implemented in #33
