### ISSUE TITLE
in ios slider does not working 

### ISSUE THREAD

**Issue by umerhayat54** [alabsi91/reanimated-color-picker#35]
### Description

in ios slider does not work but in Android, it works fine.

yes, put  'react-native-reanimated/plugin'  in  babel.config.js 

all steps I did as your mentioned in the documentation, but does not work

<img width="408" alt="Screenshot 2023-05-21 at 3 12 04 PM" src="https://github.com/alabsi91/reanimated-color-picker/assets/67622257/d9266846-69b3-4430-93e5-fea1eb8f3f41">

https://github.com/alabsi91/reanimated-color-picker/assets/67622257/a0fbf67e-ab22-4b3c-b033-0020d354d37d

### Steps to reproduce

you can use any example code 

### Reanimated Color Picker version

2.3.0

### React Native version

0.71.7

### React Native Reanimated version

3.1.0

### React Native Gesture Handler version

2.10.1

### Platforms

iOS

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

**Comment by alabsi91** [comment]
React Native Reanimated version `3.1.0` supports the New Architecture exclusively on the latest minor release of React Native `0.72.0+`. I hope this is the issue you are facing, as it can be resolved by upgrading or downgrading to the compatible version.

**Comment by umerhayat54** [comment]
> 

yes I am using react-native-reanimated version 3.1.0 but still facing same issue

**Comment by umerhayat54** [comment]
> 

yes I am using react-native-reanimated version 3.1.0 but still facing same issue

**Comment by alabsi91** [comment]
Try using React Native Reanimated version `3.0.2`, which should be compatible with React Native version `0.71.7`. If it doesn't work, consider trying the older architecture (Paper) to help determine the issue.

**Comment by umerhayat54** [comment]
okay thanks lets me try it

**Comment by umerhayat54** [comment]
> Try using React Native Reanimated version `3.0.2`, which should be compatible with React Native version `0.71.7`. If it doesn't work, consider trying the older architecture (Paper) to help determine the issue.

no luck bro
