### ISSUE TITLE
cant read useSharedValue, useAnimatedStyle

### ISSUE THREAD

**Issue by dimasaf** [alabsi91/reanimated-color-picker#38]
### Description

getting this error message 'TypeError: (0 , _$$_REQUIRE(...).useSharedValue) is not a function' whenever im importing useSharedValue, useAnimatedStyle

### Steps to reproduce

import useSharedValue, useAnimatedStyle 

### Reanimated Color Picker version

2.3.2

### React Native version

0.66

### React Native Reanimated version

1.7.0

### React Native Gesture Handler version

1.9

### Platforms

Android, iOS

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

**Comment by alabsi91** [comment]
You are using old versions of RN-reanimated and RN-gesture handler. You need version 2.0.0 and above. Please make sure to follow the installation instructions for RN-reanimated https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/
