### ISSUE TITLE
Add ability to pass initial color

### ISSUE THREAD

**Issue by lukebars** [alabsi91/reanimated-color-picker#42]
### description

It would be really useful to be able to pass the initial color when opening the color panel. I could look into adding it as a functionality if any help is needed.

**Comment by alabsi91** [comment]
The `value` prop can be serves as the initial color. Unlike the `value` prop in the `TextInput` component, When it's linked to a state, you can still change the color, and when the state updates, the color picker will automatically update accordingly. If this isn't the behavior you're seeking, please provide further clarification.

**Comment by lukebars** [comment]
How did I miss that 🫣 Thanks!
