### ISSUE TITLE
Bug: At least Panel1 and HueSlider have a weird behaviour when choose a pure color (black or white)

### ISSUE THREAD

**Issue by KarlosQ** [alabsi91/reanimated-color-picker#43]
### Description

The problem is Panel1 can modifiy HueSlider position when you move to a pure black or pure white (see video).

HueSlider is move too from right to left if you move to the righest position.

https://github.com/alabsi91/reanimated-color-picker/assets/15233913/5af5741c-fe3e-4de8-88d4-1ed3c4015599

This occours in iOS and Android

Example Code:

```jsx
  const [internalColor, setInternalColor] = useState<string>(color);

  const onColorSelect = ({ hex }: { hex: string }) => setInternalColor(hex);
  
  return (
          <ColorPicker
            value={internalColor}
            sliderThickness={16}
            thumbSize={32}
            thumbShape="circle"
            onComplete={onColorSelect}
            boundedThumb
          >
            <Panel1  />
            <HueSlider  />
            <View>
              <View>
                <Text>{translate('addIncomeForm.customColorPicker.hex')}</Text>
                <InputWidget
                  disableAlphaChannel
                  formats={['HEX']}
                />
              </View>
              <View>
                <Text>{translate('addIncomeForm.customColorPicker.rgb')}</Text>
                <InputWidget
                  disableAlphaChannel
                  formats={['RGB']}
                />
              </View>
            </View>
          </ColorPicker>
)
```

### Steps to reproduce

1. Move the Panel1 to a pure black or pure white
2. You can see that HueSlider automatic move to left position

### Reanimated Color Picker version

2.3.4

### React Native version

0.71.13

### React Native Reanimated version

3.5.4

### React Native Gesture Handler version

2.13.1

### Platforms

Android, iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

**Comment by fervailanti** [comment]
+1 👀

**Comment by alabsi91** [comment]
This occurs when a color is selected, triggering the `onComplete` event, which in your case, sets a state with the selected color. The color picker then updates the thumbs positions based on the color stored in the state. For `white` and `black` colors, the hue is set to `0`.

To work around this issue, it is advisable not to link a state to the color picker's `value` prop for now. I will investigate further and attempt to find a solution. If you have any suggestions, please feel free to share them.

**Comment by KarlosQ** [comment]
Ok thanks!
