### ISSUE TITLE
The lib is crashing my App

### ISSUE THREAD

**Issue by felipefaaria** [alabsi91/reanimated-color-picker#46]
### Description

I'm having a memory leak problem when using the library, when I do excessive color change actions on the panel or slider the app crashes and closes. One of the solutions I thought of would be to activate the input or slider only in the ColorPicker OnComplete action and not automatically when the user changes the color but I don't know how to implement it:
<ColorPicker
				value="red"
				onComplete={onSelectColor}
				boundedThumb
				thumbSize={18}
				thumbStyle={{ borderWidth: 10 }}
				thumbInnerStyle={{ backgroundColor: 'transparent' }}
			>
				<Panel1
					style={{
						height: 150,
					}}
				/>

				<InputWidget
					containerStyle={{
						marginTop: 10,
					}}
					inputTitleStyle={{ display: 'none' }}
					iconStyle={{
						display: 'none',
						width: 0,
					}}
					inputStyle={{
						height: 30,
						width: 85,
						backgroundColor: theme.colors.back1,
						borderColor: theme.colors.sysGrey4,
						alignSelf: 'flex-end',
						textTransform: 'uppercase',
						color: theme.colors.text1,
						fontSize: 15,
						borderRadius: 5,
						marginRight: 0,
					}}
				/>

				<HueSlider
					style={{ marginTop: 10, borderRadius: 22 }}
					sliderThickness={18}
				/>

### Steps to reproduce

1. I suddenly change color on the panel
2. I suddenly change color on the slider
3. The app displays a not responding message

### Reanimated Color Picker version

2.3.2

### React Native version

0.66.3

### React Native Reanimated version

2.2.4

### React Native Gesture Handler version

2.8.0

### Platforms

Android, iOS

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

**Comment by alabsi91** [comment]
Did you test it on a production build? Because `React Native Reanimated` and `React Native`, in general, run slower on the debug build. It can't keep up with fast changes, especially when the `Preview` or the `InputWidget` is used.
