### ISSUE TITLE
ColorPicker Panel3 is not working properly in ScrollView 

### ISSUE THREAD

**Issue by mukesh-simform** [alabsi91/reanimated-color-picker#57]
### Description

ColorPicker is not working properly when using Panel3 and wrapping that component in ScrollView, It works fine when disabling the scroll in ScrollView. Ideally, it should work seamlessly with ScrollView as well

### Steps to reproduce

1. Create a component using ColorPicker and Panel3
2. Use a component in a screen and wrap that in ScrollView
3. ColorPicker doesn't work properly with scroll 

### Reanimated Color Picker version

2.4.2

### React Native version

0.68.0

### React Native Reanimated version

2.11.0

### React Native Gesture Handler version

2.5.0

### Platforms

Android, iOS

### JavaScript runtime

V8

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Release mode

**Comment by alabsi91** [comment]
Hey @mukesh-simform , please try using React Native Gesture Handler ScrollView. It automatically manages gestures.
```js
import { ScrollView } from 'react-native-gesture-handler'; 
```
Let me know if this resolves your issue.

**Comment by mukesh-simform** [comment]
Yes, It's working as expected. Thank you!
