### ISSUE TITLE
Is there a way to modify the thumb scaling value?

### ISSUE THREAD

**Issue by mobily** [alabsi91/reanimated-color-picker#66]
Hey there! 👋 This is probably one of the best color pickers! Awesome work :) 

I was wondering if there's a way to adjust thumb scaling when a pan gesture starts, and as far as I can see, it isn't possible (yet). Do you want me to open a new PR with the implementation of this feature?

**Comment by alabsi91** [comment]
@mobily Thank you. No need to open a PR; I'm already working on version 3, and I'm considering adding something to control the thumb scale animation. Probably, I will do it tomorrow. I will let you know when it's ready.

**Comment by mobily** [comment]
@alabsi91 that's great to hear! let me know if you need any assistance :) (I'm already using v3-rc1 which you published an hour ago 😆 I haven't spotted any bugs so far)

**Comment by alabsi91** [comment]
Implemented in #67 

@mobily, if you have any suggestions or feedback, please let me know.

To test:
```console
npm i reanimated-color-picker@next
```
