### ISSUE TITLE
HSV convertion error

### ISSUE THREAD

**Issue by Wolk9** [alabsi91/reanimated-color-picker#72]
### Description

When I use the colorpicker, the library calculates all the color convention values, but the HSV variant throws an error:

`index.ts:1359 [colorKit.HSV] An error occurred while attempting to convert the provided parameter into an `HSV` color. As a result, the default color "black" will be used instead.`

I use the `<Panel5 />` picker and the hex value as output. I don't use the HSV at all. 

### Steps to reproduce

1. Implement Colorpicker
2. choose a color
3. See log. 

### Reanimated Color Picker version

3.0.1

### React Native version

0.72.6

### React Native Reanimated version

~3.3.0

### React Native Gesture Handler version

~2.12.0

### Platforms

Android, iOS, Web

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

**Comment by alabsi91** [comment]
Did you find the fix? I was just about to look into it.
