### ISSUE TITLE
Property `text` was whitelisted both as UI and native prop. Please remove it from one of the lists., js engine: hermes

### ISSUE THREAD

**Issue by julian-gargicevich** [alabsi91/reanimated-color-picker#74]
### Description

I'm randomly getting this error with reanimated latest version, and I think it might be related to the Preview componet and its animatedProps.

Will do more research later and complete with more info.

### Steps to reproduce

No steps

### Reanimated Color Picker version

3.0.3

### React Native version

0.73.4

### React Native Reanimated version

3.6.2

### React Native Gesture Handler version

2.14.0

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Fabric (New Architecture)

### Build type

Release mode

**Comment by alabsi91** [comment]
I couldn't replicate the issue on my side; however, the code responsible is located at [src/components/PreviewText.tsx](https://github.com/alabsi91/reanimated-color-picker/blob/main/src/components/PreviewText.tsx). It's a workaround to make an animatable text. I found this related issue that you can check: https://github.com/software-mansion/react-native-reanimated/issues/5432#issuecomment-1832915677

**Comment by Nehal-Zeller** [comment]
I've also been getting this since I integrated the package

    "reanimated-color-picker": "^4.0.0",
    "react-native": "0.75.5",
    "react-native-reanimated": "3.16.1",
    "react-native-gesture-handler": "^2.20.2",


Error: ReanimatedError
[Reanimated] Property `text` was whitelisted both as UI and native prop. Please remove it from one of the lists.


<img width="919" alt="Image" src="https://github.com/user-attachments/assets/de43609f-7baa-4694-924d-f7fbd39af768" />
