### ISSUE TITLE
Changing color value from Panel3 is not working (state or useSharedValue)

### ISSUE THREAD

**Issue by loupmasneri** [alabsi91/reanimated-color-picker#75]
### Description

https://github.com/alabsi91/reanimated-color-picker/assets/58427600/c4839ee8-1173-43a1-b2ab-72738e2c9e8c

I am just copy pasting one of your examples but it is not working on my side.
color.hex is not moving when I press anywhere on the Color picker.
selectedColor.value is not updating.

Plus I am inside a react-native Modal, I am using ScrollView from react-native-gesture-handler and it is not working as expected, i cant move inside the Panel3.
https://github.com/alabsi91/reanimated-color-picker/blob/main/Example/src/Panel3Saturation.tsx

```
const selectedColor = useSharedValue(colors.cards.black);

  const onColorSelect = (color: returnedResults) => {
    'worklet';
    console.log('color.hex:', color.hex);
    selectedColor.value = color.hex;
  };

  const backgroundColorStyle = useAnimatedStyle(() => ({
    backgroundColor: selectedColor.value,
  }));
  
  return (
    <Animated.View style={[styles.header, backgroundColorStyle]}>
        <Text>Test</Text>
        <ScrollView style={styles.scrollView}>
          <View style={styles.colorPickerContainer}>
            <ColorPicker
              thumbSize={THUMB_SIZE}
              style={styles.colorPicker}
              value={selectedColor.value}
              onChange={onColorSelect}>
              <Panel3 />
            </ColorPicker>
          </View>
      </ScrollView>
    </Animated.View>
  )
```
Thank you for your help!

### Steps to reproduce

Copy paste this example:
https://github.com/alabsi91/reanimated-color-picker/blob/main/Example/src/Panel3Saturation.tsx

### Reanimated Color Picker version

^3.0.3

### React Native version

0.73.4

### React Native Reanimated version

^3.7.0

### React Native Gesture Handler version

^2.15.0

### Platforms

Android, iOS

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

**Comment by alabsi91** [comment]
Sorry, I can't replicate the issue on my side. I used the same library versions and the example you mentioned. Please provide a repository if possible.

**Comment by loupmasneri** [comment]
You have your background color changing and you have your ColorPicker inside a ScrollView inside a Modal ? Can you show me your code maybe ?

**Comment by loupmasneri** [comment]
> Sorry, I can't replicate the issue on my side. I used the same library versions and the example you mentioned. Please provide a repository if possible.

You have your background color changing and you have your ColorPicker inside a ScrollView inside a Modal ? Can you show me your code maybe ?

**Comment by alabsi91** [comment]
Yes, The code is the same as the example code. I replaced the color picker container `View` with a `ScrollView` from 'react-native-gesture-handler' and wrap it with `GestureHandlerRootView` like so:
```jsx
import { GestureHandlerRootView, ScrollView } from 'react-native-gesture-handler';

<GestureHandlerRootView>
  <ScrollView style={styles.pickerContainer}>
    {/* Example Code */}
  </ScrollView>
</GestureHandlerRootView>

```

**Comment by loupmasneri** [comment]
> Yes, The code is the same as the example code. I replaced the color picker container `View` with a `ScrollView` from 'react-native-gesture-handler' and wrap it with `GestureHandlerRootView` like so:
> 
> ```js
> import { GestureHandlerRootView, ScrollView } from 'react-native-gesture-handler';
> 
> <GestureHandlerRootView>
>   <ScrollView style={styles.pickerContainer}>
>     {/* Example Code */}
>   </ScrollView>
> </GestureHandlerRootView>
> ```

Can you copy paste the code I had send to see if you encounter the same issues as me ?

**Comment by alabsi91** [comment]
Please provide a repository of a React Native project that replicates the issue. Otherwise, I really can't see a way to help.
